language: python
python:
  - 2.6
  - 2.7
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
  - sudo apt-get install -qq libxml2-dev libxslt-dev
install:
  - python bootstrap.py
  - bin/buildout -q -t 5 buildout:parts=test
script:
  - bin/test
